import { InquiryForm } from '@/components/inquiry-form';
export const metadata={title:'Talk with Oakheart Lab',description:'Request a free website preview or discuss a companion app, AI automation, or customer support.'};
const services:Record<string,{title:string;heading:string;body:string}>={
'mobile-app':{title:'Companion mobile app',heading:'Keep customers coming back.',body:'Give customers a convenient place to book, manage visits, and stay connected. Tell us what your app should help them do.'},
'back-office':{title:'AI back-office automation',heading:'Less busywork. More time for customers.',body:'Connect forms, booking updates, and staff tasks across your systems. Tell us which recurring work you want to simplify.'},
'customer-support':{title:'AI customer support',heading:'Help customers get answers.',body:'Support grounded in your services and policies, with a handoff to your team when needed. Tell us what customers ask most.'},
'ai-workflow':{title:'Customer & staff tools',heading:'What could work better?',body:'Tell us about a recurring task and the systems involved.'}
};
export default async function Contact({searchParams}:{searchParams:Promise<{interest?:string}>}){const {interest}=await searchParams;const service=interest&&Object.hasOwn(services,interest)?services[interest]:undefined;if(service)return <main className="wrap contact-layout"><div><p className="eyebrow">{service.title}</p><h1>{service.heading}</h1><p className="intro">{service.body}</p><div className="contact-details"><p>We’ll follow up by email. Sending an inquiry does not commit you to a project. These services are separate from the free website preview.</p><a className="text-link" href="mailto:yilun@oakheartlab.com">Email Oakheart Lab</a></div></div><InquiryForm ai service={service.title}/></main>;
return <main className="wrap contact-layout"><div><p className="eyebrow">FREE PREVIEW · NO OBLIGATION</p><h1>See what’s possible<br/><em>for your business.</em></h1><p className="intro">Explore a tailored website preview. See one price to complete, connect, and launch it before you commit.</p><ul className="bullet-list"><li>Designed around your business.</li><li>Try the proposed booking experience.</li><li>Your existing website stays unchanged.</li></ul><p className="caption">For qualified businesses considering a website project.</p><div className="contact-details"><p>We’ll email to arrange a short conversation about your project and preview timing.</p><a className="text-link" href="mailto:yilun@oakheartlab.com?subject=Website%20preview">yilun@oakheartlab.com</a></div></div><InquiryForm/></main>}
