import {Button} from '@/components/ui/button';
import Link from '@/components/site-link';
export const metadata={title:'How we improve customer experience',description:'Understand customer questions, make choosing and booking easier, and check whether the changes help.'};
export default function Approach(){return <main><section className="page-hero"><div className="wrap"><p className="eyebrow">OUR APPROACH</p><h1>Make it easy for customers.<br/><em>Make it work for your team.</em></h1><p className="intro">Find where customers get stuck and where your team does extra work. Build the connections that make the experience easier for both.</p></div></section>
<section className="section wrap">{[
['Help customers choose.','Show who each service suits, what it includes, and what it costs. Answer the questions people bring from search and AI tools.','Make the differences between options clear before asking customers to commit.'],
['Carry the choice into booking.','Check that the selected service and customer details carry through wherever the booking system supports it. Test the full path on a phone.','A customer who chooses a service should not have to hunt for it again.'],
['Make every booking useful to your team.','Check what the customer receives and where the booking details go. Connect confirmations and follow-up around the systems you use.','The customer knows how to prepare. Your team knows what is booked and what still needs attention.'],
['Measure what matters.','Agree success measures before launch. Track suitable inquiries, confirmed bookings, and manual work where the data allows.','Use the results to choose what to improve next. Account for changes in traffic, pricing, and availability.']
].map(([t,b,q],i)=><article className="principle" key={t}><div><p className="eyebrow">0{i+1}</p></div><div><h2>{t}</h2><p className="principle-body">{b}</p><p className="principle-example">{q}</p></div></article>)}</section>
<section className="soft-section"><div className="section wrap content-grid"><h2>The problem comes first.<br/>The tools follow.</h2><div className="richtext"><p>AI has expanded what businesses can do. We use it to solve a specific problem: answering customer questions, reducing repetitive work, or building a better service experience.</p><p>Sometimes the answer is AI. Sometimes it’s clearer information or a simple system connection. We choose what works, then check whether it helps your customers and team.</p></div></div></section>
<section className="section wrap content-grid" id="launch"><h2>We finish the job.</h2><div className="richtext"><p>Your website is ready when customers can use it and your team can rely on it.</p><ul className="bullet-list"><li>Booking and inquiry paths tested on mobile and desktop.</li><li>Connections checked against your existing systems.</li><li>Your team ready to manage the site after launch.</li></ul></div></section>
<section className="closing"><div className="wrap"><p className="eyebrow">START WITH YOUR BUSINESS</p><h2>See your website.<br/><em>Reimagined.</em></h2><div className="closing-bottom"><p>Explore a free tailored preview and see one price<br/>to complete, connect, and launch. No obligation to buy.</p><Button asChild className="cta light"><Link href="/contact">Request your free preview</Link></Button></div><p className="caption" style={{marginTop:18}}>For qualified businesses.</p></div></section></main>}
