"use client";
import { useEffect, useRef, useState } from "react";
import Link from "@/components/site-link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
function makeId(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const s=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;}

export function InquiryForm({ai=false,service}:{ai?:boolean;service?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState("");
 const [requestId,setRequestId]=useState("");
 const successRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(receipt)successRef.current?.focus()},[receipt]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const data=new FormData(e.currentTarget);try{const id=requestId||makeId();setRequestId(id);const params=new URLSearchParams(window.location.search);const response=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:id,name:data.get('name'),email:data.get('email'),website:data.get('website'),message:data.get('message'),companyFax:data.get('companyFax'),interest:['ai-workflow','mobile-app','back-office','customer-support'].includes(params.get('interest')||'')?params.get('interest'):'website-booking',source:(params.get('utm_source')||'direct').slice(0,120),campaign:(params.get('utm_campaign')||'').slice(0,200)})});const result=await response.json() as {error?:string;reference:string};if(!response.ok)throw new Error(result.error||'We couldn’t save your inquiry. Please try again or email us.');setReceipt(result.reference);}catch(err){setError(err instanceof Error?err.message:'Please try again or email us.');}finally{setBusy(false);}}
 if(receipt)return <div className="form-panel"><div className="notice" role="status" tabIndex={-1} ref={successRef}><p className="eyebrow">INQUIRY RECEIVED</p><h2>Thanks for the context.</h2><p>{ai?'Your service inquiry has been saved. We will follow up by email to discuss the next step. No paid project has been agreed.':'Your preview request has been saved. We will follow up by email to discuss fit and timing. No preview slot or paid project is confirmed yet.'}</p><p className="caption">Reference: {receipt}</p><p className="caption">This form doesn’t send an automatic confirmation email.</p></div><div className="success-actions"><Link className="text-link" href="/services">Explore the offer</Link><Link className="text-link" href="/">Back to home</Link></div></div>;
 return <form onSubmit={submit} className="form-panel"><h2>{ai?(service||'Discuss your workflow'):'Request your free preview'}</h2><div className="form-field"><Label htmlFor="name">Your name</Label><Input id="name" name="name" autoComplete="name" required maxLength={100} placeholder="Full name"/></div><div className="form-field"><Label htmlFor="email">Work email</Label><Input id="email" name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@yourbusiness.com"/></div><div className="form-field"><Label htmlFor="website">Business website <span style={{fontWeight:400}}>(optional)</span></Label><Input id="website" name="website" type="text" autoComplete="url" maxLength={500} placeholder="yourbusiness.com"/></div><div className="form-field"><Label htmlFor="message">What would you like to improve?</Label><Textarea id="message" name="message" required minLength={10} maxLength={3000} placeholder={ai?"Tell us what you want to improve and which systems you use.":"What does your business do, and what would you like your website or booking process to do better?"}/></div><div className="hp" aria-hidden="true"><label htmlFor="companyFax">Leave this empty</label><input id="companyFax" name="companyFax" tabIndex={-1} autoComplete="off"/></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button className="cta" type="submit" disabled={busy}>{busy?'Saving your inquiry…':(ai?'Send inquiry':'Request a free preview')}</Button><p className="form-note">We use these details to respond to your inquiry. You won’t be added to a newsletter. Please don’t include passwords or sensitive customer data. <Link href="/privacy">Privacy details</Link>.</p></form>
}
