import Link from "@/components/site-link";
import { Button } from "@/components/ui/button";
export function Logo(){return <Link href="/" className="brand" aria-label="Oakheart Lab home"><span className="brand-mark" aria-hidden="true">o<span>l</span></span><span>oakheart<span className="brand-lab">lab</span></span></Link>}
export function Header(){return <header className="site-header"><div className="wrap nav"><Logo/><nav aria-label="Main navigation"><Link href="/services">What we do</Link><Link href="/work/booking-flow">Our approach</Link><Link href="/about">About</Link><Link href="/insights">Articles & advice</Link></nav><Button asChild className="nav-cta"><Link href="/contact">Free preview</Link></Button></div></header>}
export function Footer(){return <footer className="footer wrap"><div><Logo/><p>Connect the customer experience.<br/>Coordinate the work behind it.</p></div><div><span className="eyebrow">EXPLORE</span><Link href="/services">What we build</Link><Link href="/work/booking-flow">Our approach</Link><Link href="/insights">Articles & advice</Link><Link href="/guides">Buyer’s guide</Link><Link href="/services#process">How we work together</Link></div><div><span className="eyebrow">SAY HELLO</span><a href="mailto:yilun@oakheartlab.com">yilun@oakheartlab.com</a><Link href="/contact">Request a free preview</Link><Link href="/privacy">Privacy</Link></div><div className="footer-bottom"><span>© 2026 Oakheart Lab</span><span>Independent thinking. Thoughtful building.</span></div></footer>}
export function SectionTitle({number,label,title}:{number:string,label:string,title:React.ReactNode}){return <div><p className="eyebrow">{number} / {label}</p><h2>{title}</h2></div>}
export function Closing(){return <section className="closing"><div className="wrap"><p className="eyebrow">LET’S START WITH YOUR BUSINESS</p><h2>See the possibilities.<br/><em>Then decide.</em></h2><div className="closing-bottom"><p>A free tailored preview for qualified businesses.<br/>No obligation to buy.</p><Button asChild className="cta light"><Link href="/contact">Request a free preview</Link></Button></div></div></section>}
export function ImprovementExample(){return <aside className="improvement-example" aria-labelledby="improvement-title"><p className="eyebrow">YOUR FREE PREVIEW</p><h2 id="improvement-title">Built for your business.<br/>{' '}Yours to explore.</h2><p className="example-context">Explore a new website experience for your business.</p><dl className="improvement-list">{[
['See your new direction','Tailored copy and design using your business and services.'],
['Try the customer journey','Explore how visitors could choose and book. Simulated steps are clearly marked.'],
['Decide with a clear price','One price to complete, connect, and launch. Proceed only if it’s right for you.']
].map(([title,body],i)=><div key={title}><span className="improvement-number" aria-hidden="true">0{i+1}</span><div><dt>{title}</dt><dd>{body}</dd></div></div>)}</dl><Link className="text-link" href="/services#measurement">How the free preview works</Link></aside>}
